# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'psgUser'
        regionName: 'eu-north-1'
        imageSource: 'imageId'
        imageId: '$(Build.Repository.Name):v1'
        repositoryName: 'frontend/webapp2'
        autoCreateRepository: true





# trigger:
#   branches:
#     include:
#       - main

# jobs:
#   - job: BuildAndPushDockerImage
#     displayName: "Build and Push Docker Image"
#     pool:
#       vmImage: 'ubuntu-latest'

#     steps:
#       - checkout: self

#       - task: Docker@2
#         displayName: 'Build Docker Image'
#         inputs:
#           containerRegistry: 'yourContainerRegistry'
#           repository: 'yourRepository'
#           command: 'build'
#           Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
#           tags: 'latest'

#       - task: Docker@2
#         displayName: 'Push Docker Image to ECR'
#         inputs:
#           containerRegistry: 'yourContainerRegistry'
#           repository: 'yourRepository'
#           command: 'push'
#           tags: 'latest'
#           azureSubscriptionEndpoint: 'yourAzureSubscriptionEndpoint'
#           azureContainerRegistry: 'yourAzureContainerRegistry'

