trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'
  

steps:
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: ECRPushImage@1
  displayName: push to ecr repo 2
  inputs:
    awsCredentials: 'psgUser'
    regionName: 'eu-north-1'
    imageSource: 'imagename'
    sourceImageName: '780356874729.dkr.ecr.eu-north-1.amazonaws.com/frontend/web-app'
    sourceImageTag: 'v1'
    repositoryName: 'frontend/web-app2'
    autoCreateRepository: true


# - task: AWSCLI@1
#   displayName: 'Push Docker image to AWS ECR'
#   inputs:
#     awsCredentials: 'psgUser'  # Replace with the name of your AWS service connection in Azure DevOps
#     regionName: 'eu-north-1'  # Replace with your AWS region name
#     commandName: 'ecr'
#     commandArgs: 'get-login-password --region eu-north-1 --profile psg | docker login --username AWS --password-stdin 780356874729.dkr.ecr.eu-north-1.amazonaws.com'


    
  # - task: Docker@2
  #   inputs:
  #     command: 'buildAndPush'
  #     Dockerfile: '**/Dockerfile'
  



