trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    command: 'build'
    dockerfile: '**/Dockerfile'  # Replace with the path to your Dockerfile
  displayName: 'Build Docker image'
  name: 'dockerBuild'

- task: Bash@3
  displayName: 'set Docker image name variable'
  inputs:
    targetType: 'inline'
    script: |
      imageId=$(docker inspect --format='{{.ID}}' $(dockerBuild.ImageName))
      echo "##vso[task.setvariable variable=imageName]$imageId"

- task: ECRPushImage@1
  displayName: 'Push Docker image to AWS ECR'
  inputs:
    awsCredentials: 'psgUser' 
    regionName: 'eu-north-1'
    repositoryName: 'frontend/web-app3'  
    imageName: '$(imageName)' #pass imageID variable set earlier
    imageTag: 'v1'  
    autoCreateRepository: true

