trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'  # Replace with the path to your Dockerfile

- task: ECRPushImage@1
  displayName: 'Push Docker image to AWS ECR'
  inputs:
    awsCredentials: 'psgUser'  # Replace with the name of your AWS service connection in Azure DevOps
    regionName: 'eu-north-1'  # Replace with your AWS region name
    #imageSource: 'build'  # Specify 'build' to use the Docker image built in the previous step
    repositoryName: 'frontend/web-app3'  # Replace with your Amazon ECR repository name
    imageTag: 'v1'  # Replace with the tag for the Docker image
    autoCreateRepository: true
    
  # - task: Docker@2
  #   inputs:
  #     command: 'buildAndPush'
  #     Dockerfile: '**/Dockerfile'


