trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'
  
jobs:
- job: BuildAndPush
  displayName: 'Build and Push Docker Image'
  steps:
  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: 'v1'
      # containerRegistry: 'yourContainerRegistry'  # Replace with your Azure Container Registry
      # repository: 'yourRepository'  # Replace with your repository name
      # addPipelineData: true  # This enables capturing pipeline data as output variables

  - script: |
      echo "##vso[task.setvariable variable=imageName;isOutput=true]$(Build.Repository.Name):$(Build.BuildNumber)-v1"
    displayName: 'Set Image Name Variable'

  - task: ECRPushImage@1
    displayName: push to ecr repo 2
    inputs:
      awsCredentials: 'psgUser'
      regionName: 'eu-north-1'
      imageSource: 'image'
      sourceImageName: $[dependencies.BuildAndPush.outputs['Build Docker image.imageName']]
      sourceImageTag: 'v1'
      repositoryName: 'frontend/web-app2'
      autoCreateRepository: true
